;;; org-projectile-helm-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from org-projectile-helm.el

(autoload 'org-projectile-helm-template-or-project "org-projectile-helm" "\
Select a project or `org-capture' template and record a TODO.

If provided, CAPTURE-TEMPLATE-FOR-PROJECT will be the capture
template used for project TODO capture.

(fn &optional CAPTURE-TEMPLATE-FOR-PROJECT)" t)
(register-definition-prefixes "org-projectile-helm" '("org-projectile-helm-"))

;;; End of scraped data

(provide 'org-projectile-helm-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; org-projectile-helm-autoloads.el ends here
